version: '3'
services:
  railsapp:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    env_file:
      - '.env'
    volumes:
      - "./:/desafio_backend"
